### ISSUE TITLE
dotplot in viridis color palette 

### ISSUE THREAD

**Issue by GregorD96** [DaniFlat/qRAT#1]
Hi Daniel,
first of all congrats on the cool application! I have been looking for something like this for a long time and was never happy with the existing R-packages. I have found a minor 'cosmetic' issue. When plotting the dotplot and using the viridis color scheme it uses shades of green instead of the categorical colors it uses for the barplots (see attached image). Maybe this could be implemented in the next release :)? Thanks and keep up the good work.
Best,
Gregor
![dot_and_barplot](https://user-images.githubusercontent.com/60294248/181475026-8cb1c923-6e8b-4855-9e8f-4674ba68fc65.png)

**Comment by DaniFlat** [comment]
Hi Gregor,
thank you, I am glad to hear that the tool is useful for you :)
You are absolutely right, I never noticed that. There will be a fix for this in the next version. 
If you encounter any other problems with the tool while analyzing your data, please feel free to open another Issue or contact me. I am always thankful for suggestions that help to continuously improve the tool.
Best regards,
Daniel

**Comment by DaniFlat** [comment]
this is fixed in version 0.1.6
